apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cometbft
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: cometbft
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 10s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: hostname
