prometheus:
  prometheusSpec:
    maximumStartupDurationSeconds: 120

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  adminPassword: prom-operator

  dashboardsProvider:
    enabled: true

  extraConfigmapMounts:
    - name: cometbft-dashboard
      mountPath: /var/lib/grafana/dashboards/cometbft/cometbft.json
      subPath: cometbft.json
      configMap: cometbft-dashboard
    - name: cometbft-dashboards-provider
      mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
      subPath: dashboards.yaml
      configMap: cometbft-dashboards-provider
